services:

  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app
    
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  db:
    image: mongo:latest