services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  db:
    image: mongo:latest
    container_name: mongo-db
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"